# Generated by Django 5.1 on 2024-08-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_id", models.CharField(max_length=64)),
                ("product_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("quantity_sold", models.IntegerField()),
                ("rating", models.FloatField()),
                ("review_count", models.IntegerField()),
            ],
        ),
    ]
